export type SiteLocale = "en" | "zh";

export const defaultSiteLocale: SiteLocale = "zh";

export const siteLocaleCookieName = "site-locale";

export const siteCopy = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      now: "Now",
      checklists: "Checklists",
      blog: "Blog",
      notes: "Notes",
      updates: "Updates",
      timeline: "Timeline",
    },
    frame: {
      tagline: "Personal expression and workflow",
      dashboard: "Workspace",
      admin: "Admin",
      footerBlog: "Writing",
      footerTimeline: "Timeline",
      footerWorkspace: "Workspace",
    },
    common: {
      backHome: "Back Home",
      managePosts: "Manage Posts",
      manageChecklists: "Manage Checklists",
      relatedLink: "Open Link",
      relatedPost: "View Post",
      relatedUpdates: "View Updates",
      page: "Page",
      updatedAt: "Updated",
      pinned: "Pinned",
      featured: "Featured",
      done: "Done",
      pending: "Pending",
      expandItems: "Expand",
      completionNote: "Completion Note",
      published: "Published",
      readMinutes: "min read",
      publicVisibility: "Public",
      privateVisibility: "Private",
      localeLabel: "Language",
    },
    home: {
      checklistTitle: "Current Checklists",
      checklistDescription: "Recent checklist content is expanded right on the homepage.",
      checklistEmpty:
        "No public checklist yet. Start with a course-like checklist such as Advanced Mathematics.",
      checklistGroups: "Groups",
      checklistItems: "Items",
      checklistCompleted: "done",
      updatesTitle: "Recent Updates",
      updatesDescription: "Updates are shown directly on the homepage with less jumping around.",
      updatesEmpty:
        "No public update yet. Once you publish one, this becomes the lightest activity stream on the homepage.",
    },
    blog: {
      latestWaiting: "Waiting for the first post",
      statsPosts: "Posts",
      statsTags: "Tags",
      statsLatest: "Latest",
      emptyTitle: "No public post yet",
      emptyBody: "Once you publish the first Post from the admin panel, it will appear here automatically.",
    },
    notes: {
      statsNotes: "Notes",
      statsPinned: "Pinned",
      statsMoods: "Moods",
      emptyTitle: "No public note yet",
      emptyBody: "Publish your first public Note and this stream will start to grow.",
    },
    updates: {
      statsUpdates: "Updates",
      statsLinked: "Linked",
      statsTypes: "Types",
      emptyTitle: "No public update yet",
      emptyBody: "The Update collection is ready. Publish one and this feed will start filling in automatically.",
    },
    timeline: {
      statsEvents: "Events",
      statsFeatured: "Featured",
      statsTypes: "Types",
      emptyTitle: "Timeline is still empty",
      emptyBody: "Publish your first TimelineEvent and this page will start building a long-term narrative.",
    },
    checklists: {
      statsChecklists: "Checklists",
      statsGroups: "Groups",
      statsCompleted: "Completed",
      badgeChecklist: "Checklist",
      groups: "Groups",
      items: "Items",
      completed: "Completed",
      groupCompleted: "done",
      emptyTitle: "No public checklist yet",
      emptyBody: "Create a Checklist in admin and add groups and items. It will show up here automatically.",
    },
    page: {
      waitingBody: "Create a Page in admin and set its slug to `{slug}` to show the final content here.",
      missingTitle: "Page Not Found | SunnyPanel",
      metaSuffix: "page",
    },
    blogPost: {
      backList: "Back to Blog",
      approxRead: "Approx.",
      overview: "Article Overview",
      publishedAt: "Published",
      updatedAt: "Updated",
      readingTime: "Reading Time",
      articleLayer:
        "This article belongs to SunnyPanel's public writing layer and stays connected with the homepage, Blog list, and Timeline.",
      notFound: "Post Not Found | SunnyPanel",
    },
  },
  zh: {
    nav: {
      home: "首页",
      about: "About",
      now: "Now",
      checklists: "清单",
      blog: "Blog",
      notes: "Notes",
      updates: "Updates",
      timeline: "Timeline",
    },
    frame: {
      tagline: "个人表达与私有工作流",
      dashboard: "私有工作台",
      admin: "进入后台",
      footerBlog: "写作",
      footerTimeline: "时间线",
      footerWorkspace: "工作台",
    },
    common: {
      backHome: "返回首页",
      managePosts: "管理文章",
      manageChecklists: "管理清单",
      relatedLink: "查看关联资源",
      relatedPost: "查看关联文章",
      relatedUpdates: "查看关联动态",
      page: "页面",
      updatedAt: "最近更新",
      pinned: "置顶",
      featured: "精选",
      done: "已完成",
      pending: "未完成",
      expandItems: "展开条目",
      completionNote: "完成备注",
      published: "发布时间",
      readMinutes: "分钟阅读",
      publicVisibility: "公开",
      privateVisibility: "私有",
      localeLabel: "语言",
    },
    home: {
      checklistTitle: "当前清单",
      checklistDescription: "直接在首页展开最近的清单内容，不再额外放一层跳转按钮。",
      checklistEmpty: "还没有公开的 Checklist。你可以先在后台建一个课程型清单，比如“高等数学”。",
      checklistGroups: "分组",
      checklistItems: "条目",
      checklistCompleted: "完成",
      updatesTitle: "最近更新",
      updatesDescription: "Update 直接在首页展示正文片段，减少来回跳转。",
      updatesEmpty: "还没有公开的 Update。发布后，这里会成为首页最轻量的动态入口。",
    },
    blog: {
      latestWaiting: "等待第一篇文章",
      statsPosts: "公开文章",
      statsTags: "主题标签",
      statsLatest: "最近发布",
      emptyTitle: "还没有公开文章",
      emptyBody: "后台内容模型已经接好。你创建第一篇公开并发布的 Post 之后，这里就会自动出现。",
    },
    notes: {
      statsNotes: "公开短文",
      statsPinned: "置顶条目",
      statsMoods: "情绪标签",
      emptyTitle: "还没有公开短文",
      emptyBody: "等你从后台发布第一条公开 Note，这里就会开始积累属于 SunnyPanel 的短内容流。",
    },
    updates: {
      statsUpdates: "公开动态",
      statsLinked: "带链接记录",
      statsTypes: "类型覆盖",
      emptyTitle: "还没有公开动态",
      emptyBody: "后台 `Update` collection 已经可用。发布内容后，这里会自动形成一条时间顺序的动态流。",
    },
    timeline: {
      statsEvents: "公开节点",
      statsFeatured: "精选事件",
      statsTypes: "事件类型",
      emptyTitle: "时间线还是空的",
      emptyBody: "等你在后台添加第一条 `TimelineEvent` 并公开发布后，这里就会开始形成年度回顾结构。",
    },
    checklists: {
      statsChecklists: "清单",
      statsGroups: "分组",
      statsCompleted: "已完成",
      badgeChecklist: "Checklist",
      groups: "分组",
      items: "条目",
      completed: "已完成",
      groupCompleted: "已完成",
      emptyTitle: "还没有公开清单",
      emptyBody: "先在后台新建一个 Checklist，再加入分组和条目，这里就会自动展示。",
    },
    page: {
      waitingBody: "在后台创建一个 `Page`，并把 slug 设为 `{slug}`，这里就会显示正式内容。",
      missingTitle: "页面未找到 | SunnyPanel",
      metaSuffix: "页面",
    },
    blogPost: {
      backList: "返回文章列表",
      approxRead: "约",
      overview: "文章概览",
      publishedAt: "发布时间",
      updatedAt: "最近更新",
      readingTime: "阅读时长",
      articleLayer: "这篇文章属于 SunnyPanel 的公开写作层，会和首页、Blog 列表以及 Timeline 一起构成长期可回看的个人表达系统。",
      notFound: "文章未找到 | SunnyPanel",
    },
  },
} as const;

export function resolveSiteLocale(value?: string | null): SiteLocale {
  return value === "en" ? "en" : defaultSiteLocale;
}

export function getSiteCopy(locale: SiteLocale) {
  return siteCopy[locale];
}
