/**
 * Performance Trace — Diagnostic instrumentation for the Agent chat pipeline.
 *
 * Feature flags (all default OFF):
 *   AGENT_PERF_TRACE=1         → enable timing, emit summary to SSE done event
 *   AGENT_VERBOSE_PERF_TRACE=1 → also emit per-phase detail, LLM/DB/tool records
 *
 * Production:
 *   Only requestId, totalMs, firstTokenMs, phase summary are emitted.
 *   Full detail arrays (llmCalls, dbCalls, toolCalls) are omitted.
 *
 * Safety:
 *   Never records full prompts, full history, full user input, or full tool results.
 *   Only records: names, token counts, durations, success/failure status.
 */

/* ──── Feature flags ──── */

export const isPerfTraceEnabled = (): boolean => process.env.AGENT_PERF_TRACE === "1";

export const isVerbosePerfTraceEnabled = (): boolean => process.env.AGENT_VERBOSE_PERF_TRACE === "1";

export const isProduction = (): boolean => process.env.NODE_ENV === "production";

/* ──── Record types ──── */

export type LLMCallRecord = {
  name: string;
  model?: string;
  inputTokens?: number;
  outputTokens?: number;
  durationMs: number;
  success: boolean;
  error?: string;
};

export type DBCallRecord = {
  name: string;
  /** "real" = actual Payload DB call; "synthetic" = aggregate estimate (e.g. workspace parallel queries) */
  kind: "real" | "synthetic";
  table?: string;
  durationMs: number;
  rows?: number;
  success: boolean;
  error?: string;
};

export type ToolCallRecord = {
  name: string;
  durationMs: number;
  sideEffect: boolean;
  success: boolean;
  error?: string;
};

/* ──── Phase timing ──── */

export type PhaseTiming = {
  requestParseMs?: number;
  loadThreadMs?: number;
  /** Session Coordinator sub-phases (nested under coordinator) */
  normalizeSessionMs?: number;
  rulePreCheckMs?: number;
  transitionEngineMs?: number;
  reconcileMs?: number;
  /** Router / arbitration */
  routerChainMs?: number;
  llmRouterMs?: number;
  arbitrationMs?: number;
  /** Context & orchestration */
  contextBuilderMs?: number;
  orchestrationMs?: number;
  /** Safety & execution */
  toolGateMs?: number;
  toolExecutionMs?: number;
  /** Response & streaming */
  responseGenerationMs?: number;
  streamingMs?: number;
  /** Persistence */
  persistMs?: number;
};

/** Top-level phases that wrap nested sub-phases */
export type TopLevelPhaseName =
  | "request"
  | "session"
  | "router"
  | "context"
  | "orchestration"
  | "safety"
  | "execution"
  | "response"
  | "persist";

export type TopLevelPhaseSummary = {
  name: TopLevelPhaseName;
  durationMs: number;
  /** Whether any nested phase failed */
  hasError: boolean;
};

/* ──── Route perf info ──── */

export type RoutePerfInfo = {
  routeHintSource?: string;
  routeHintConfidence?: number;
  routeHintApplied?: boolean;
  routeHintConflict?: boolean;
  finalIntent?: string;
};

/* ──── First token timing ──── */

export type FirstTokenTiming = {
  /** Server-side: when the first response token is generated by the LLM */
  serverFirstTokenMs?: number;
  /** Server-side: when the first SSE token event is enqueued */
  serverFirstChunkSentMs?: number;
  /** Client-reported: when the browser first fires onToken with block "response" */
  clientFirstTokenMs?: number;
  /** Client-reported: when React commits the first token to DOM (best-effort via rAF) */
  firstRenderMs?: number;
};

/* ──── Main trace ──── */

export type AgentPerformanceTrace = {
  requestId: string;
  threadId?: number;
  userId?: number;
  /** Total wall-clock from request arrival to response completion */
  totalMs: number;
  /** First-token timing (server + client) */
  firstToken?: FirstTokenTiming;
  /** Top-level phase durations (always included in summary) */
  phaseSummary: TopLevelPhaseSummary[];
  /** Detailed per-phase timing (verbose only) */
  phases: PhaseTiming;
  /** LLM call records (verbose only) */
  llmCalls: LLMCallRecord[];
  /** LLM call count (always included) */
  llmCallCount: number;
  /** DB call records (verbose only) */
  dbCalls: DBCallRecord[];
  /** DB call count (always included) */
  dbCallCount: number;
  /** Tool call records (verbose only) */
  toolCalls: ToolCallRecord[];
  /** Route perf info */
  routeInfo?: RoutePerfInfo;
  /** Feature flags snapshot */
  flags: {
    agentSessionCoordinatorEnabled: boolean;
    streamingEnabled: boolean;
    perfTraceEnabled: boolean;
    verbosePerfTrace: boolean;
  };
};

/* ──── Production summary (SSE-safe) ──── */

export type AgentPerformanceTraceSummary = {
  requestId: string;
  threadId?: number;
  totalMs: number;
  firstToken?: FirstTokenTiming;
  phaseSummary: TopLevelPhaseSummary[];
  llmCallCount: number;
  dbCallCount: number;
  routeInfo?: RoutePerfInfo;
  flags: AgentPerformanceTrace["flags"];
};

/** Strip verbose detail for production SSE */
export const toPerfTraceSummary = (trace: AgentPerformanceTrace): AgentPerformanceTraceSummary => ({
  requestId: trace.requestId,
  threadId: trace.threadId,
  totalMs: trace.totalMs,
  firstToken: trace.firstToken,
  phaseSummary: trace.phaseSummary,
  llmCallCount: trace.llmCallCount,
  dbCallCount: trace.dbCallCount,
  routeInfo: trace.routeInfo,
  flags: trace.flags,
});

/* ──── Timer ──── */

export type AgentPerformanceTimer = ReturnType<typeof createPerformanceTimer>;

/**
 * Create a performance timer for one Agent chat request.
 *
 * Usage:
 *   const timer = createPerformanceTimer(requestId);
 *   const elapsed = timer.measurePhase("loadThread", () => loadThread());
 *   timer.recordLLMCall({ name: "router", durationMs: 1200, ... });
 *   const trace = timer.snapshot({ threadId, userId });
 */
export const createPerformanceTimer = (requestId: string) => {
  const startMs = performance.now();
  const phaseStarts = new Map<string, number>();

  const llmCalls: LLMCallRecord[] = [];
  const dbCalls: DBCallRecord[] = [];
  const toolCalls: ToolCallRecord[] = [];
  const topLevelPhases: TopLevelPhaseSummary[] = [];

  let firstToken: FirstTokenTiming = {};

  // ── Phase timing ──

  /** Start timing a phase. Must be paired with endPhase() or use measurePhase(). */
  const startPhase = (name: string): void => {
    phaseStarts.set(name, performance.now());
  };

  /** End timing a phase. Returns duration in ms, or 0 if phase was never started. */
  const endPhase = (name: string, success = true, _error?: string): number => {
    const start = phaseStarts.get(name);
    if (start === undefined) return 0;
    phaseStarts.delete(name);
    return performance.now() - start;
  };

  /**
   * Measure a block of work with try/finally, always recording duration.
   * Returns the block's return value.
   */
  const measurePhase = <T>(name: string, fn: () => T): T => {
    startPhase(name);
    try {
      const result = fn();
      endPhase(name, true);
      return result;
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      endPhase(name, false, errorMsg);
      throw err;
    }
  };

  /**
   * Measure an async block of work with try/finally, always recording duration.
   */
  const measurePhaseAsync = async <T>(name: string, fn: () => Promise<T>): Promise<T> => {
    startPhase(name);
    try {
      const result = await fn();
      endPhase(name, true);
      return result;
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      endPhase(name, false, errorMsg);
      throw err;
    }
  };

  /** Record a top-level phase (aggregates nested sub-phases). */
  const recordTopLevelPhase = (name: TopLevelPhaseName, durationMs: number, hasError = false): void => {
    topLevelPhases.push({ name, durationMs, hasError });
  };

  // ── First token ──

  const markServerFirstToken = (): void => {
    if (firstToken.serverFirstTokenMs === undefined) {
      firstToken.serverFirstTokenMs = performance.now() - startMs;
    }
  };

  const markServerFirstChunkSent = (): void => {
    if (firstToken.serverFirstChunkSentMs === undefined) {
      firstToken.serverFirstChunkSentMs = performance.now() - startMs;
    }
  };

  /** Set client-side timing (reported back from frontend via SSE or next request) */
  const setClientTiming = (clientFirstTokenMs?: number, firstRenderMs?: number): void => {
    if (clientFirstTokenMs !== undefined && firstToken.clientFirstTokenMs === undefined) {
      firstToken.clientFirstTokenMs = clientFirstTokenMs;
    }
    if (firstRenderMs !== undefined && firstToken.firstRenderMs === undefined) {
      firstToken.firstRenderMs = firstRenderMs;
    }
  };

  // ── Records ──

  const recordLLMCall = (call: LLMCallRecord): void => {
    llmCalls.push(call);
  };

  const recordDBCall = (call: DBCallRecord): void => {
    dbCalls.push(call);
  };

  const recordToolCall = (call: ToolCallRecord): void => {
    toolCalls.push(call);
  };

  /** Collect all remaining phase durations from the phaseStarts map */
  const collectPhaseTimings = (): PhaseTiming => {
    const timings: PhaseTiming = {};
    // Only include phases that have been started+ended (removed from map)
    // plus any still-running phases (treated as error)
    for (const [name, start] of phaseStarts) {
      // Phase was started but never ended → treat as incomplete
      const duration = performance.now() - start;
      phaseStarts.delete(name);
      (timings as Record<string, number>)[name + "Ms"] = duration;
    }
    return timings;
  };

  // ── Snapshot ──

  const snapshot = (overrides: {
    phases: PhaseTiming;
    routeInfo?: RoutePerfInfo;
    threadId?: number;
    userId?: number;
    streamingEnabled?: boolean;
    coordinatorEnabled?: boolean;
  }): AgentPerformanceTrace => {
    const totalMs = performance.now() - startMs;
    // Merge explicitly tracked phases with any remaining phaseStarts
    const residualPhases = collectPhaseTimings();
    const mergedPhases: PhaseTiming = { ...overrides.phases, ...residualPhases };

    return {
      requestId,
      threadId: overrides.threadId,
      userId: overrides.userId,
      totalMs,
      firstToken: Object.keys(firstToken).length > 0 ? { ...firstToken } : undefined,
      phaseSummary: [...topLevelPhases],
      phases: mergedPhases,
      llmCalls: [...llmCalls],
      llmCallCount: llmCalls.length,
      dbCalls: [...dbCalls],
      dbCallCount: dbCalls.length,
      toolCalls: [...toolCalls],
      routeInfo: overrides.routeInfo,
      flags: {
        agentSessionCoordinatorEnabled: overrides.coordinatorEnabled ?? false,
        streamingEnabled: overrides.streamingEnabled ?? true,
        perfTraceEnabled: isPerfTraceEnabled(),
        verbosePerfTrace: isVerbosePerfTraceEnabled(),
      },
    };
  };

  /** Production-safe SSE payload */
  const snapshotForSSE = (overrides: {
    phases: PhaseTiming;
    routeInfo?: RoutePerfInfo;
    threadId?: number;
    userId?: number;
    streamingEnabled?: boolean;
    coordinatorEnabled?: boolean;
  }): AgentPerformanceTrace | AgentPerformanceTraceSummary => {
    const full = snapshot(overrides);
    if (isProduction() && !isVerbosePerfTraceEnabled()) {
      return toPerfTraceSummary(full);
    }
    if (isVerbosePerfTraceEnabled()) {
      return full;
    }
    // Development without verbose flag: include detail
    return full;
  };

  return {
    startMs: () => startMs,
    startPhase,
    endPhase,
    measurePhase,
    measurePhaseAsync,
    recordTopLevelPhase,
    markServerFirstToken,
    markServerFirstChunkSent,
    setClientTiming,
    recordLLMCall,
    recordDBCall,
    recordToolCall,
    snapshot,
    snapshotForSSE,
  };
};
