/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    notes: Note;
    updates: Update;
    checklists: Checklist;
    'timeline-events': TimelineEvent;
    plans: Plan;
    'schedule-items': ScheduleItem;
    'plan-reviews': PlanReview;
    'agent-threads': AgentThread;
    'agent-runs': AgentRun;
    'agent-action-receipts': AgentActionReceipt;
    'agent-thread-events': AgentThreadEvent;
    'agent-memories': AgentMemory;
    'agent-suggestions': AgentSuggestion;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    checklists: ChecklistsSelect<false> | ChecklistsSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'schedule-items': ScheduleItemsSelect<false> | ScheduleItemsSelect<true>;
    'plan-reviews': PlanReviewsSelect<false> | PlanReviewsSelect<true>;
    'agent-threads': AgentThreadsSelect<false> | AgentThreadsSelect<true>;
    'agent-runs': AgentRunsSelect<false> | AgentRunsSelect<true>;
    'agent-action-receipts': AgentActionReceiptsSelect<false> | AgentActionReceiptsSelect<true>;
    'agent-thread-events': AgentThreadEventsSelect<false> | AgentThreadEventsSelect<true>;
    'agent-memories': AgentMemoriesSelect<false> | AgentMemoriesSelect<true>;
    'agent-suggestions': AgentSuggestionsSelect<false> | AgentSuggestionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'agent-settings': AgentSetting;
  };
  globalsSelect: {
    'agent-settings': AgentSettingsSelect<false> | AgentSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 可选。用于后台和工作台里显示你的称呼。
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 简短说明这张图片的内容，方便无障碍阅读和 SEO。
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * 保留旧 schema 兼容；slug 现在默认可直接手动输入。
   */
  generateSlug?: boolean | null;
  /**
   * 可直接手动输入。若留空，系统会尝试根据标题自动生成。
   */
  slug: string;
  /**
   * 先写一句 1 到 2 行的摘要，后面可以再慢慢补。
   */
  summary: string;
  /**
   * Dashboard Writing 使用的结构化富文本内容。
   */
  contentRich:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentText?: string | null;
  contentExcerpt?: string | null;
  contentOutline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentVersion?: string | null;
  /**
   * 迁移和回滚来源；Dashboard 不写入这个字段。
   */
  legacyContentMarkdown?: string | null;
  /**
   * 可选。先不填也没关系。
   */
  tags?: string[] | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  /**
   * 可选。用于前台排序和显示时间。
   */
  publishedAt?: string | null;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  /**
   * Dashboard Writing 使用的结构化富文本内容。
   */
  contentRich:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentText?: string | null;
  contentExcerpt?: string | null;
  contentOutline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentVersion?: string | null;
  /**
   * 迁移和回滚来源；Dashboard 不写入这个字段。
   */
  legacyContentMarkdown?: string | null;
  mood?: string | null;
  category: string;
  pinned?: boolean | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: number;
  /**
   * 先选一个最接近的类型即可。
   */
  type: 'life' | 'work' | 'project';
  /**
   * Dashboard Writing 使用的结构化富文本内容。
   */
  contentRich:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentText?: string | null;
  contentExcerpt?: string | null;
  contentOutline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentVersion?: string | null;
  /**
   * 迁移和回滚来源；Dashboard 不写入这个字段。
   */
  legacyContentMarkdown?: string | null;
  /**
   * 可选。需要时再补。
   */
  link?: string | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklists".
 */
export interface Checklist {
  id: number;
  /**
   * 例如：高等数学、线性代数、阅读计划。
   */
  title: string;
  /**
   * 保留旧 schema 兼容；slug 现在默认可直接手动输入。
   */
  generateSlug?: boolean | null;
  /**
   * 可直接手动输入。若留空，系统会尝试根据标题自动生成。
   */
  slug: string;
  summary?: string | null;
  /**
   * 先创建章节或模块，再往每个分组里补具体条目。
   */
  groups?:
    | {
        title: string;
        /**
         * 把具体知识点或任务写在这里。标记完成后会自动写入时间线。
         */
        items?:
          | {
              title: string;
              description?: string | null;
              isCompleted?: boolean | null;
              /**
               * 可选。不填时，时间线会自动使用当前时间。
               */
              completedAt?: string | null;
              completionNote?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  /**
   * 可选。用于前台排序和显示时间。
   */
  publishedAt?: string | null;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  title: string;
  description?: string | null;
  /**
   * 记录这个节点真正发生的时间。
   */
  eventDate: string;
  type: 'milestone' | 'project' | 'life' | 'study' | 'exam' | 'agent';
  sourceType?: ('checklist' | 'schedule' | 'plan' | 'manual' | 'agent') | null;
  relatedPost?: (number | null) | Post;
  relatedUpdate?: (number | null) | Update;
  relatedChecklist?: (number | null) | Checklist;
  /**
   * 系统内部使用，用来避免重复生成完成记录。
   */
  relatedTaskKey?: string | null;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  title: string;
  description?: string | null;
  /**
   * 为未来接入自动 Agent 预留：这项计划主要由谁推进。
   */
  executionMode: 'manual' | 'hybrid' | 'agent';
  /**
   * 计划所属领域，影响 Agent 拆解策略。
   */
  domain: 'study' | 'work' | 'travel' | 'fitness' | 'creative' | 'other';
  /**
   * 这项计划在 Agent 工作流里的当前阶段。
   */
  agentState: 'idle' | 'ready' | 'running' | 'blocked' | 'review';
  /**
   * 给未来 Agent 的目标、边界、输入和完成标准。
   */
  agentBrief?: string | null;
  /**
   * 把这项计划正在产出的文章、短札、更新、清单、时间线节点或页面关联进来。
   */
  linkedContent?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'notes';
            value: number | Note;
          }
        | {
            relationTo: 'updates';
            value: number | Update;
          }
        | {
            relationTo: 'checklists';
            value: number | Checklist;
          }
        | {
            relationTo: 'timeline-events';
            value: number | TimelineEvent;
          }
        | {
            relationTo: 'pages';
            value: number | Page;
          }
      )[]
    | null;
  /**
   * 通常由 Agent Run 自动回写，用来追踪最近一次执行记录。
   */
  lastAgentRun?: (number | null) | AgentRun;
  state: 'backlog' | 'active' | 'paused' | 'done';
  status: 'draft' | 'published';
  priority: 'low' | 'medium' | 'high';
  startDate?: string | null;
  dueDate?: string | null;
  visibility: 'public' | 'private';
  /**
   * 由 Agent 拆解的阶段、里程碑和任务。通常由 compose_plan 自动填充。
   */
  phases?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 例如：每天2小时，周末4小时。由 Agent 根据计划类型推荐。
   */
  weeklyRhythm?: string | null;
  totalEstimatedDays?: number | null;
  progress?: number | null;
  prerequisites?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 编排依赖图、中间结果与最近一次 orchestration 元数据。
   */
  agentContext?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 编排器拆解的子任务状态（id、label、intent、agentRole、status）。
   */
  subtasks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * 保留旧 schema 兼容；slug 现在默认可直接手动输入。
   */
  generateSlug?: boolean | null;
  /**
   * 可直接手动输入。若留空，系统会尝试根据标题自动生成。
   */
  slug: string;
  /**
   * Dashboard Writing 使用的结构化富文本内容。
   */
  contentRich:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentText?: string | null;
  contentExcerpt?: string | null;
  contentOutline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentVersion?: string | null;
  /**
   * 迁移和回滚来源；Dashboard 不写入这个字段。
   */
  legacyContentMarkdown?: string | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs".
 */
export interface AgentRun {
  id: number;
  title: string;
  workflow:
    | 'readiness-audit'
    | 'planning'
    | 'content-draft'
    | 'publishing-review'
    | 'sync'
    | 'weekly-review'
    | 'automation';
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
  trigger: 'manual' | 'scheduled' | 'webhook' | 'agent';
  /**
   * 创建这条 AgentRun 的用户，用于自定义 API 与回滚执行的归属校验。
   */
  user?: (number | null) | User;
  /**
   * 这次运行的目标、边界或验收标准。
   */
  goal?: string | null;
  /**
   * 用 1 到 3 句话说明这次运行完成了什么，留下了什么问题。
   */
  summary?: string | null;
  /**
   * 给下一次运行或人工接手留下可继续推进的动作。
   */
  nextAction?: string | null;
  relatedPlan?: (number | null) | Plan;
  /**
   * 把这次运行读写过的内容挂进来，便于后续审计。
   */
  relatedContent?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'notes';
            value: number | Note;
          }
        | {
            relationTo: 'updates';
            value: number | Update;
          }
        | {
            relationTo: 'checklists';
            value: number | Checklist;
          }
        | {
            relationTo: 'timeline-events';
            value: number | TimelineEvent;
          }
        | {
            relationTo: 'plan-reviews';
            value: number | PlanReview;
          }
        | {
            relationTo: 'agent-memories';
            value: number | AgentMemory;
          }
        | {
            relationTo: 'pages';
            value: number | Page;
          }
      )[]
    | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * 可选。便于之后分析执行成本。
   */
  durationMs?: number | null;
  /**
   * 按时间顺序记录这次运行的关键步骤。
   */
  steps?:
    | {
        recordedAt?: string | null;
        level: 'info' | 'warn' | 'error';
        message: string;
        id?: string | null;
      }[]
    | null;
  /**
   * dry-run / execute 阶段解析出的真实影响范围。
   */
  affectedDocuments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  beforeSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 暂不自动执行，仅保存后续实现 rollback 所需的结构化数据。
   */
  rollbackPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rollbackAvailable?: boolean | null;
  /**
   * 同一复合意图拆解与批量确认共享的关联 ID。
   */
  orchestrationId?: string | null;
  /**
   * 执行该次写操作的专业 Agent 角色。
   */
  agentRole?: ('plan' | 'schedule' | 'review' | 'memory' | 'content' | 'query' | 'orchestrator') | null;
  model?: string | null;
  provider?: string | null;
  tokenUsage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  trace?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-reviews".
 */
export interface PlanReview {
  id: number;
  title: string;
  scope: 'overall' | 'plan';
  health: 'healthy' | 'attention' | 'risk';
  plan?: (number | null) | Plan;
  summary: string;
  /**
   * 由 Agent 根据 Plan / Checklist / Timeline / AgentRun 等真实数据生成。
   */
  metrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recommendations?:
    | {
        content: string;
        id?: string | null;
      }[]
    | null;
  source: 'agent' | 'manual';
  reviewedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-memories".
 */
export interface AgentMemory {
  id: number;
  title: string;
  type: 'preference' | 'project_context' | 'writing_style' | 'workflow_rule' | 'fact';
  content: string;
  /**
   * 语义检索用 embedding（number[]）。由 Agent 在保存记忆时自动写入。
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  confidence: number;
  sourceThread?: (number | null) | AgentThread;
  sourceRun?: (number | null) | AgentRun;
  lastUsedAt?: string | null;
  status: 'active' | 'archived';
  /**
   * AgentMemory 只用于单用户私有工作台，暂不允许公开。
   */
  visibility: 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-threads".
 */
export interface AgentThread {
  id: number;
  title: string;
  status: 'active' | 'closed';
  user: number | User;
  /**
   * 保留最近的对话上下文，供事务型 Agent 继续承接。
   */
  messages?:
    | {
        role: 'user' | 'assistant';
        content: string;
        recordedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 例如等待用户补 completion note。写入前由 Agent schema 校验。
   */
  pendingAction?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 自动压缩长会话，供 Agent 在不读取完整消息历史时继续承接目标、结果和待处理动作。
   */
  summary?: string | null;
  summaryUpdatedAt?: string | null;
  summaryMessageCount?: number | null;
  lastIntent?:
    | (
        | 'answer_question'
        | 'create_plan'
        | 'append_plan_item'
        | 'complete_plan_item'
        | 'compose_plan'
        | 'compose_schedule_item'
        | 'compose_timeline_event'
        | 'add_completion_note'
        | 'save_memory'
        | 'query_progress'
        | 'query_plan_progress'
        | 'evaluate_plan'
        | 'schedule_plan'
        | 'weekly_review'
        | 'reschedule_item'
        | 'cancel_schedule_item'
        | 'clarify'
        | 'modify_record'
        | 'delete_record'
        | 'capability_query'
        | 'query_checklist_progress'
        | 'query_memory'
        | 'query_plan'
        | 'query_schedule'
        | 'query_timeline'
      )
    | null;
  lastEngine?: ('glm' | 'openai' | 'zai' | 'heuristic' | 'workflow' | 'model' | 'openai-compatible') | null;
  lastConfidence?: number | null;
  lastInteractionAt?: string | null;
  /**
   * JSON 字符串数组，用于分类检索。
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-items".
 */
export interface ScheduleItem {
  id: number;
  title: string;
  description?: string | null;
  date: string;
  /**
   * 使用 HH:mm，例如 09:30。全天事项可留空。
   */
  startTime?: string | null;
  /**
   * 使用 HH:mm，例如 10:30。全天事项可留空。
   */
  endTime?: string | null;
  isAllDay?: boolean | null;
  status: 'planned' | 'done' | 'skipped' | 'canceled';
  priority: 'low' | 'medium' | 'high';
  sourceType: 'plan' | 'checklist' | 'manual' | 'agent';
  category?: ('course' | 'study' | 'plan_action' | 'agent' | 'exam' | 'default') | null;
  relatedPlan?: (number | null) | Plan;
  relatedChecklist?: (number | null) | Checklist;
  relatedChecklistItemKey?: string | null;
  agentBrief?: string | null;
  createdBy: 'manual' | 'agent';
  conflictNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-action-receipts".
 */
export interface AgentActionReceipt {
  id: number;
  key: string;
  actionId: string;
  intent: string;
  operation: 'execute' | 'rollback';
  status: 'pending' | 'succeeded' | 'failed' | 'indeterminate';
  user: number | User;
  thread: number | AgentThread;
  response?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rollbackPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-thread-events".
 */
export interface AgentThreadEvent {
  id: number;
  eventKey: string;
  turnId: string;
  eventType: 'legacy_bootstrap' | 'user_received' | 'assistant_completed' | 'turn_failed' | 'projection_failed';
  schemaVersion: number;
  thread: number | AgentThread;
  user: number | User;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recordedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-suggestions".
 */
export interface AgentSuggestion {
  id: number;
  title: string;
  reason: string;
  suggestedPrompt: string;
  /**
   * 由 Agent 生成，用于避免同一条建议反复出现。
   */
  uniqueKey: string;
  source: 'dashboard' | 'plan' | 'content' | 'content-lifecycle' | 'timeline' | 'agent-run' | 'review';
  riskLevel: 'low' | 'medium' | 'high';
  status: 'pending' | 'accepted' | 'dismissed' | 'done';
  relatedPlan?: (number | null) | Plan;
  relatedContent?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'notes';
            value: number | Note;
          }
        | {
            relationTo: 'updates';
            value: number | Update;
          }
        | {
            relationTo: 'checklists';
            value: number | Checklist;
          }
        | {
            relationTo: 'timeline-events';
            value: number | TimelineEvent;
          }
        | {
            relationTo: 'pages';
            value: number | Page;
          }
      )[]
    | null;
  createdBy: 'agent' | 'manual';
  dismissedAt?: string | null;
  acceptedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'updates';
        value: number | Update;
      } | null)
    | ({
        relationTo: 'checklists';
        value: number | Checklist;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'schedule-items';
        value: number | ScheduleItem;
      } | null)
    | ({
        relationTo: 'plan-reviews';
        value: number | PlanReview;
      } | null)
    | ({
        relationTo: 'agent-threads';
        value: number | AgentThread;
      } | null)
    | ({
        relationTo: 'agent-runs';
        value: number | AgentRun;
      } | null)
    | ({
        relationTo: 'agent-action-receipts';
        value: number | AgentActionReceipt;
      } | null)
    | ({
        relationTo: 'agent-thread-events';
        value: number | AgentThreadEvent;
      } | null)
    | ({
        relationTo: 'agent-memories';
        value: number | AgentMemory;
      } | null)
    | ({
        relationTo: 'agent-suggestions';
        value: number | AgentSuggestion;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  contentRich?: T;
  contentText?: T;
  contentExcerpt?: T;
  contentOutline?: T;
  contentVersion?: T;
  legacyContentMarkdown?: T;
  tags?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  contentRich?: T;
  contentText?: T;
  contentExcerpt?: T;
  contentOutline?: T;
  contentVersion?: T;
  legacyContentMarkdown?: T;
  mood?: T;
  category?: T;
  pinned?: T;
  coverImage?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  type?: T;
  contentRich?: T;
  contentText?: T;
  contentExcerpt?: T;
  contentOutline?: T;
  contentVersion?: T;
  legacyContentMarkdown?: T;
  link?: T;
  coverImage?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklists_select".
 */
export interface ChecklistsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  groups?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              isCompleted?: T;
              completedAt?: T;
              completionNote?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  eventDate?: T;
  type?: T;
  sourceType?: T;
  relatedPost?: T;
  relatedUpdate?: T;
  relatedChecklist?: T;
  relatedTaskKey?: T;
  isFeatured?: T;
  sortOrder?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  executionMode?: T;
  domain?: T;
  agentState?: T;
  agentBrief?: T;
  linkedContent?: T;
  lastAgentRun?: T;
  state?: T;
  status?: T;
  priority?: T;
  startDate?: T;
  dueDate?: T;
  visibility?: T;
  phases?: T;
  weeklyRhythm?: T;
  totalEstimatedDays?: T;
  progress?: T;
  prerequisites?: T;
  agentContext?: T;
  subtasks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-items_select".
 */
export interface ScheduleItemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  isAllDay?: T;
  status?: T;
  priority?: T;
  sourceType?: T;
  category?: T;
  relatedPlan?: T;
  relatedChecklist?: T;
  relatedChecklistItemKey?: T;
  agentBrief?: T;
  createdBy?: T;
  conflictNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-reviews_select".
 */
export interface PlanReviewsSelect<T extends boolean = true> {
  title?: T;
  scope?: T;
  health?: T;
  plan?: T;
  summary?: T;
  metrics?: T;
  recommendations?:
    | T
    | {
        content?: T;
        id?: T;
      };
  source?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-threads_select".
 */
export interface AgentThreadsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  user?: T;
  messages?:
    | T
    | {
        role?: T;
        content?: T;
        recordedAt?: T;
        id?: T;
      };
  pendingAction?: T;
  summary?: T;
  summaryUpdatedAt?: T;
  summaryMessageCount?: T;
  lastIntent?: T;
  lastEngine?: T;
  lastConfidence?: T;
  lastInteractionAt?: T;
  tags?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs_select".
 */
export interface AgentRunsSelect<T extends boolean = true> {
  title?: T;
  workflow?: T;
  status?: T;
  trigger?: T;
  user?: T;
  goal?: T;
  summary?: T;
  nextAction?: T;
  relatedPlan?: T;
  relatedContent?: T;
  startedAt?: T;
  completedAt?: T;
  durationMs?: T;
  steps?:
    | T
    | {
        recordedAt?: T;
        level?: T;
        message?: T;
        id?: T;
      };
  affectedDocuments?: T;
  beforeSnapshot?: T;
  afterSnapshot?: T;
  rollbackPayload?: T;
  rollbackAvailable?: T;
  orchestrationId?: T;
  agentRole?: T;
  model?: T;
  provider?: T;
  tokenUsage?: T;
  trace?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-action-receipts_select".
 */
export interface AgentActionReceiptsSelect<T extends boolean = true> {
  key?: T;
  actionId?: T;
  intent?: T;
  operation?: T;
  status?: T;
  user?: T;
  thread?: T;
  response?: T;
  rollbackPayload?: T;
  error?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-thread-events_select".
 */
export interface AgentThreadEventsSelect<T extends boolean = true> {
  eventKey?: T;
  turnId?: T;
  eventType?: T;
  schemaVersion?: T;
  thread?: T;
  user?: T;
  payload?: T;
  recordedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-memories_select".
 */
export interface AgentMemoriesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  content?: T;
  embedding?: T;
  confidence?: T;
  sourceThread?: T;
  sourceRun?: T;
  lastUsedAt?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-suggestions_select".
 */
export interface AgentSuggestionsSelect<T extends boolean = true> {
  title?: T;
  reason?: T;
  suggestedPrompt?: T;
  uniqueKey?: T;
  source?: T;
  riskLevel?: T;
  status?: T;
  relatedPlan?: T;
  relatedContent?: T;
  createdBy?: T;
  dismissedAt?: T;
  acceptedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  contentRich?: T;
  contentText?: T;
  contentExcerpt?: T;
  contentOutline?: T;
  contentVersion?: T;
  legacyContentMarkdown?: T;
  coverImage?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-settings".
 */
export interface AgentSetting {
  id: number;
  /**
   * 关闭后，系统会直接回退到环境变量里的模型配置。
   */
  enabled?: boolean | null;
  provider: 'openai-compatible' | 'openai' | 'zai';
  /**
   * 例如 OpenAI 官方接口，或 GLM 的 OpenAI-compatible 地址。
   */
  baseUrl?: string | null;
  /**
   * 例如 `gpt-5.4-mini`、`gpt-4.1-mini`、`glm-5.1`。
   */
  model?: string | null;
  /**
   * 留空时会回退到环境变量；只有管理员能在后台看到和修改这项配置。
   */
  apiKey?: string | null;
  /**
   * 可选。记录这组模型配置的用途，例如“Agent MVP / 实验用”。
   */
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-settings_select".
 */
export interface AgentSettingsSelect<T extends boolean = true> {
  enabled?: T;
  provider?: T;
  baseUrl?: T;
  model?: T;
  apiKey?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}