/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    notes: Note;
    updates: Update;
    checklists: Checklist;
    'timeline-events': TimelineEvent;
    plans: Plan;
    'plan-reviews': PlanReview;
    'agent-threads': AgentThread;
    'agent-runs': AgentRun;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    checklists: ChecklistsSelect<false> | ChecklistsSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'plan-reviews': PlanReviewsSelect<false> | PlanReviewsSelect<true>;
    'agent-threads': AgentThreadsSelect<false> | AgentThreadsSelect<true>;
    'agent-runs': AgentRunsSelect<false> | AgentRunsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'agent-settings': AgentSetting;
  };
  globalsSelect: {
    'agent-settings': AgentSettingsSelect<false> | AgentSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 可选。用于后台和工作台里显示你的称呼。
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 简短说明这张图片的内容，方便无障碍阅读和 SEO。
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * 保留旧 schema 兼容；slug 现在默认可直接手动输入。
   */
  generateSlug?: boolean | null;
  /**
   * 可直接手动输入。若留空，系统会尝试根据标题自动生成。
   */
  slug: string;
  /**
   * 先写一句 1 到 2 行的摘要，后面可以再慢慢补。
   */
  summary: string;
  /**
   * 先把核心内容写下来，格式和细节可以之后再整理。
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 可选。先不填也没关系。
   */
  tags?: string[] | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  /**
   * 可选。用于前台排序和显示时间。
   */
  publishedAt?: string | null;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  content: string;
  mood?: string | null;
  category: string;
  pinned?: boolean | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: number;
  /**
   * 先选一个最接近的类型即可。
   */
  type: 'life' | 'work' | 'project';
  content: string;
  /**
   * 可选。需要时再补。
   */
  link?: string | null;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklists".
 */
export interface Checklist {
  id: number;
  /**
   * 例如：高等数学、线性代数、阅读计划。
   */
  title: string;
  /**
   * 保留旧 schema 兼容；slug 现在默认可直接手动输入。
   */
  generateSlug?: boolean | null;
  /**
   * 可直接手动输入。若留空，系统会尝试根据标题自动生成。
   */
  slug: string;
  summary?: string | null;
  /**
   * 先创建章节或模块，再往每个分组里补具体条目。
   */
  groups?:
    | {
        title: string;
        /**
         * 把具体知识点或任务写在这里。标记完成后会自动写入时间线。
         */
        items?:
          | {
              title: string;
              description?: string | null;
              isCompleted?: boolean | null;
              /**
               * 可选。不填时，时间线会自动使用当前时间。
               */
              completedAt?: string | null;
              completionNote?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  /**
   * 可选。用于前台排序和显示时间。
   */
  publishedAt?: string | null;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  title: string;
  description?: string | null;
  /**
   * 记录这个节点真正发生的时间。
   */
  eventDate: string;
  type: 'milestone' | 'project' | 'life';
  relatedPost?: (number | null) | Post;
  relatedUpdate?: (number | null) | Update;
  relatedChecklist?: (number | null) | Checklist;
  /**
   * 系统内部使用，用来避免重复生成完成记录。
   */
  relatedTaskKey?: string | null;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  title: string;
  description?: string | null;
  /**
   * 为未来接入自动 Agent 预留：这项计划主要由谁推进。
   */
  executionMode: 'manual' | 'hybrid' | 'agent';
  /**
   * 这项计划在 Agent 工作流里的当前阶段。
   */
  agentState: 'idle' | 'ready' | 'running' | 'blocked' | 'review';
  /**
   * 给未来 Agent 的目标、边界、输入和完成标准。
   */
  agentBrief?: string | null;
  /**
   * 把这项计划正在产出的文章、短札、更新、清单、时间线节点或页面关联进来。
   */
  linkedContent?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'notes';
            value: number | Note;
          }
        | {
            relationTo: 'updates';
            value: number | Update;
          }
        | {
            relationTo: 'checklists';
            value: number | Checklist;
          }
        | {
            relationTo: 'timeline-events';
            value: number | TimelineEvent;
          }
        | {
            relationTo: 'pages';
            value: number | Page;
          }
      )[]
    | null;
  /**
   * 通常由 Agent Run 自动回写，用来追踪最近一次执行记录。
   */
  lastAgentRun?: (number | null) | AgentRun;
  state: 'backlog' | 'active' | 'paused' | 'done';
  status: 'draft' | 'published';
  priority: 'low' | 'medium' | 'high';
  startDate?: string | null;
  dueDate?: string | null;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * 保留旧 schema 兼容；slug 现在默认可直接手动输入。
   */
  generateSlug?: boolean | null;
  /**
   * 可直接手动输入。若留空，系统会尝试根据标题自动生成。
   */
  slug: string;
  /**
   * 先把页面的核心内容写出来，版式可以之后再慢慢调整。
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  status: 'draft' | 'published';
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs".
 */
export interface AgentRun {
  id: number;
  title: string;
  workflow: 'readiness-audit' | 'planning' | 'content-draft' | 'publishing-review' | 'sync' | 'automation';
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
  trigger: 'manual' | 'scheduled' | 'webhook' | 'agent';
  /**
   * 这次运行的目标、边界或验收标准。
   */
  goal?: string | null;
  /**
   * 用 1 到 3 句话说明这次运行完成了什么，留下了什么问题。
   */
  summary?: string | null;
  /**
   * 给下一次运行或人工接手留下可继续推进的动作。
   */
  nextAction?: string | null;
  relatedPlan?: (number | null) | Plan;
  /**
   * 把这次运行读写过的内容挂进来，便于后续审计。
   */
  relatedContent?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'notes';
            value: number | Note;
          }
        | {
            relationTo: 'updates';
            value: number | Update;
          }
        | {
            relationTo: 'checklists';
            value: number | Checklist;
          }
        | {
            relationTo: 'timeline-events';
            value: number | TimelineEvent;
          }
        | {
            relationTo: 'plan-reviews';
            value: number | PlanReview;
          }
        | {
            relationTo: 'pages';
            value: number | Page;
          }
      )[]
    | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * 可选。便于之后分析执行成本。
   */
  durationMs?: number | null;
  /**
   * 按时间顺序记录这次运行的关键步骤。
   */
  steps?:
    | {
        recordedAt?: string | null;
        level: 'info' | 'warn' | 'error';
        message: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-reviews".
 */
export interface PlanReview {
  id: number;
  title: string;
  scope: 'overall' | 'plan';
  health: 'healthy' | 'attention' | 'risk';
  plan?: (number | null) | Plan;
  summary: string;
  /**
   * 由 Agent 根据 Plan / Checklist / Timeline / AgentRun 等真实数据生成。
   */
  metrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recommendations?:
    | {
        content: string;
        id?: string | null;
      }[]
    | null;
  source: 'agent' | 'manual';
  reviewedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-threads".
 */
export interface AgentThread {
  id: number;
  title: string;
  status: 'active' | 'closed';
  user: number | User;
  /**
   * 保留最近的对话上下文，供事务型 Agent 继续承接。
   */
  messages?:
    | {
        role: 'user' | 'assistant';
        content: string;
        recordedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 例如等待用户补 completion note。写入前由 Agent schema 校验。
   */
  pendingAction?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastIntent?:
    | (
        | 'create_plan'
        | 'append_plan_item'
        | 'complete_plan_item'
        | 'add_completion_note'
        | 'query_progress'
        | 'evaluate_plan'
        | 'clarify'
      )
    | null;
  lastEngine?: ('glm' | 'heuristic' | 'workflow') | null;
  lastConfidence?: number | null;
  lastInteractionAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'updates';
        value: number | Update;
      } | null)
    | ({
        relationTo: 'checklists';
        value: number | Checklist;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'plan-reviews';
        value: number | PlanReview;
      } | null)
    | ({
        relationTo: 'agent-threads';
        value: number | AgentThread;
      } | null)
    | ({
        relationTo: 'agent-runs';
        value: number | AgentRun;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  content?: T;
  tags?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  content?: T;
  mood?: T;
  category?: T;
  pinned?: T;
  coverImage?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  type?: T;
  content?: T;
  link?: T;
  coverImage?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklists_select".
 */
export interface ChecklistsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  groups?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              isCompleted?: T;
              completedAt?: T;
              completionNote?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  eventDate?: T;
  type?: T;
  relatedPost?: T;
  relatedUpdate?: T;
  relatedChecklist?: T;
  relatedTaskKey?: T;
  isFeatured?: T;
  sortOrder?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  executionMode?: T;
  agentState?: T;
  agentBrief?: T;
  linkedContent?: T;
  lastAgentRun?: T;
  state?: T;
  status?: T;
  priority?: T;
  startDate?: T;
  dueDate?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-reviews_select".
 */
export interface PlanReviewsSelect<T extends boolean = true> {
  title?: T;
  scope?: T;
  health?: T;
  plan?: T;
  summary?: T;
  metrics?: T;
  recommendations?:
    | T
    | {
        content?: T;
        id?: T;
      };
  source?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-threads_select".
 */
export interface AgentThreadsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  user?: T;
  messages?:
    | T
    | {
        role?: T;
        content?: T;
        recordedAt?: T;
        id?: T;
      };
  pendingAction?: T;
  lastIntent?: T;
  lastEngine?: T;
  lastConfidence?: T;
  lastInteractionAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-runs_select".
 */
export interface AgentRunsSelect<T extends boolean = true> {
  title?: T;
  workflow?: T;
  status?: T;
  trigger?: T;
  goal?: T;
  summary?: T;
  nextAction?: T;
  relatedPlan?: T;
  relatedContent?: T;
  startedAt?: T;
  completedAt?: T;
  durationMs?: T;
  steps?:
    | T
    | {
        recordedAt?: T;
        level?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  content?: T;
  coverImage?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-settings".
 */
export interface AgentSetting {
  id: number;
  /**
   * 关闭后，系统会直接回退到环境变量里的模型配置。
   */
  enabled?: boolean | null;
  provider: 'openai-compatible' | 'openai' | 'zai';
  /**
   * 例如 OpenAI 官方接口，或 GLM 的 OpenAI-compatible 地址。
   */
  baseUrl?: string | null;
  /**
   * 例如 `gpt-5.4-mini`、`gpt-4.1-mini`、`glm-5.1`。
   */
  model?: string | null;
  /**
   * 留空时会回退到环境变量；只有管理员能在后台看到和修改这项配置。
   */
  apiKey?: string | null;
  /**
   * 可选。记录这组模型配置的用途，例如“Agent MVP / 实验用”。
   */
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-settings_select".
 */
export interface AgentSettingsSelect<T extends boolean = true> {
  enabled?: T;
  provider?: T;
  baseUrl?: T;
  model?: T;
  apiKey?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}